#!/bin/zsh
# pull resource from ORG
# Author: david.zhao@resentek.com
# Date: 2020-04-01

if test "$1" = "class"; then
  echo --get specific metadata: class:$2 alias:$3---
  sfdx force:source:retrieve -m "ApexClass:$2" -u $3
elif test "$1" = "object"; then
  echo --get specific metadata: object:$2 alias:$3---
  sfdx force:source:retrieve -m "CustomObject:$2" -u $3
elif test "$1" = "aura"; then  
  echo --get specific metadata: aura:$2 alias:$3---
  sfdx force:source:retrieve -m "AuraDefinitionBundle:$2" -u $3
elif test "$1" = "lwc"; then
  echo --get specific metadata: aura:$2 alias:$3---
  sfdx force:source:retrieve -m "LightningComponentBundle:$2" -u $3
elif test "$1" = "workflow"; then  
  echo --get specific metadata: workflow:$2 alias:$3---
  sfdx force:source:retrieve -m "Workflow:$2" -u $3
else
  echo "Command syntax: get type name alias"
fi